[package]
name = "emty-agent"
version = "0.1.6"
description = "A nothing-special coding agent"
authors = ["emty-png"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "emty_agent_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["unstable"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-dialog = "2.7.0"
tauri-plugin-fs = "2.5.0"
tauri-plugin-persisted-scope = "2.0.0"
tauri-plugin-sql = { version = "2", features = ["sqlite"] }
tauri-plugin-shell = "2.3.2"
tauri-plugin-os = "2.3.2"
tauri-plugin-http = "2"
portable-pty = "0.9"
ignore = "0.4"
globset = "0.4"
reqwest = { version = "0.12", features = ["rustls-tls"] }
scraper = "0.22"
urlencoding = "2"
grep-matcher = "0.1"
grep-regex = "0.1"
grep-searcher = "0.1"
tauri-plugin-process = "2"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-updater = "2"
tauri-plugin-window-state = "2"

[target.'cfg(windows)'.dependencies]
webview2-com = "0.38.2"
