export interface MDevPreset {
  id: string
  name: string
  api: string
}

export const ALL_PROVIDERS: MDevPreset[] = [
  { id: '302ai', name: '302.AI', api: 'https://api.302.ai/v1' },
  { id: 'abacus', name: 'Abacus', api: 'https://routellm.abacus.ai/v1' },
  { id: 'abliteration-ai', name: 'abliteration.ai', api: 'https://api.abliteration.ai/v1' },
  { id: 'aihubmix', name: 'AIHubMix', api: '' },
  { id: 'alibaba', name: 'Alibaba', api: 'https://dashscope-intl.aliyuncs.com/compatible-mode/v1' },
  { id: 'alibaba-cn', name: 'Alibaba (China)', api: 'https://dashscope.aliyuncs.com/compatible-mode/v1' },
  { id: 'alibaba-coding-plan', name: 'Alibaba Coding Plan', api: 'https://coding-intl.dashscope.aliyuncs.com/v1' },
  { id: 'alibaba-coding-plan-cn', name: 'Alibaba Coding Plan (China)', api: 'https://coding.dashscope.aliyuncs.com/v1' },
  { id: 'amazon-bedrock', name: 'Amazon Bedrock', api: '' },
  { id: 'ambient', name: 'Ambient', api: 'https://api.ambient.xyz/v1' },
  { id: 'anthropic', name: 'Anthropic', api: '' },
  { id: 'anyapi', name: 'AnyAPI', api: 'https://api.anyapi.ai/v1' },
  { id: 'atomic-chat', name: 'Atomic Chat', api: 'http://127.0.0.1:1337/v1' },
  { id: 'auriko', name: 'Auriko', api: 'https://api.auriko.ai/v1' },
  { id: 'azure', name: 'Azure', api: '' },
  { id: 'azure-cognitive-services', name: 'Azure Cognitive Services', api: '' },
  { id: 'bailing', name: 'Bailing', api: 'https://api.tbox.cn/api/llm/v1/chat/completions' },
  { id: 'baseten', name: 'Baseten', api: 'https://inference.baseten.co/v1' },
  { id: 'berget', name: 'Berget.AI', api: 'https://api.berget.ai/v1' },
  { id: 'cerebras', name: 'Cerebras', api: '' },
  { id: 'chutes', name: 'Chutes', api: 'https://llm.chutes.ai/v1' },
  { id: 'clarifai', name: 'Clarifai', api: 'https://api.clarifai.com/v2/ext/openai/v1' },
  { id: 'claudinio', name: 'Claudinio', api: 'https://api.claudin.io/v1' },
  { id: 'cloudferro-sherlock', name: 'CloudFerro Sherlock', api: 'https://api-sherlock.cloudferro.com/openai/v1/' },
  { id: 'cloudflare-ai-gateway', name: 'Cloudflare AI Gateway', api: '' },
  // eslint-disable-next-line no-template-curly-in-string
  { id: 'cloudflare-workers-ai', name: 'Cloudflare Workers AI', api: 'https://api.cloudflare.com/client/v4/accounts/${CLOUDFLARE_ACCOUNT_ID}/ai/v1' },
  { id: 'cohere', name: 'Cohere', api: '' },
  { id: 'cortecs', name: 'Cortecs', api: 'https://api.cortecs.ai/v1' },
  { id: 'crof', name: 'CrofAI', api: 'https://crof.ai/v1' },
  { id: 'drun', name: 'D.Run (China)', api: 'https://chat.d.run/v1' },
  // eslint-disable-next-line no-template-curly-in-string
  { id: 'databricks', name: 'Databricks', api: 'https://${DATABRICKS_HOST}/ai-gateway/mlflow/v1' },
  { id: 'deepinfra', name: 'Deep Infra', api: '' },
  { id: 'deepseek', name: 'DeepSeek', api: 'https://api.deepseek.com' },
  { id: 'digitalocean', name: 'DigitalOcean', api: 'https://inference.do-ai.run/v1' },
  { id: 'dinference', name: 'DInference', api: 'https://api.dinference.com/v1' },
  { id: 'evroc', name: 'evroc', api: 'https://models.think.evroc.com/v1' },
  { id: 'fastrouter', name: 'FastRouter', api: 'https://go.fastrouter.ai/api/v1' },
  { id: 'firepass', name: 'Fireworks (Firepass)', api: 'https://api.fireworks.ai/inference/v1/' },
  { id: 'fireworks-ai', name: 'Fireworks AI', api: 'https://api.fireworks.ai/inference/v1/' },
  { id: 'friendli', name: 'Friendli', api: 'https://api.friendli.ai/serverless/v1' },
  { id: 'frogbot', name: 'FrogBot', api: 'https://app.frogbot.ai/api/v1' },
  { id: 'github-copilot', name: 'GitHub Copilot', api: 'https://api.githubcopilot.com' },
  { id: 'github-models', name: 'GitHub Models', api: 'https://models.github.ai/inference' },
  { id: 'gitlab', name: 'GitLab Duo', api: '' },
  { id: 'gmicloud', name: 'GMI Cloud', api: 'https://api.gmi-serving.com/v1' },
  { id: 'google', name: 'Google', api: '' },
  { id: 'groq', name: 'Groq', api: '' },
  { id: 'helicone', name: 'Helicone', api: 'https://ai-gateway.helicone.ai/v1' },
  { id: 'hpc-ai', name: 'HPC-AI', api: 'https://api.hpc-ai.com/inference/v1' },
  { id: 'huggingface', name: 'Hugging Face', api: 'https://router.huggingface.co/v1' },
  { id: 'iflowcn', name: 'iFlow', api: 'https://apis.iflow.cn/v1' },
  { id: 'inception', name: 'Inception', api: 'https://api.inceptionlabs.ai/v1/' },
  { id: 'inceptron', name: 'Inceptron', api: 'https://api.inceptron.io/v1' },
  { id: 'inference', name: 'Inference', api: 'https://inference.net/v1' },
  { id: 'io-net', name: 'IO.NET', api: 'https://api.intelligence.io.solutions/api/v1' },
  { id: 'jiekou', name: 'Jiekou.AI', api: 'https://api.jiekou.ai/openai' },
  { id: 'kilo', name: 'Kilo Gateway', api: 'https://api.kilo.ai/api/gateway' },
  { id: 'kimi-for-coding', name: 'Kimi For Coding', api: 'https://api.kimi.com/coding/v1' },
  { id: 'kuae-cloud-coding-plan', name: 'KUAE Cloud Coding Plan', api: 'https://coding-plan-endpoint.kuaecloud.net/v1' },
  { id: 'lilac', name: 'Lilac', api: 'https://api.getlilac.com/v1' },
  { id: 'llama', name: 'Llama', api: 'https://api.llama.com/compat/v1/' },
  { id: 'llmgateway', name: 'LLM Gateway', api: 'https://api.llmgateway.io/v1' },
  { id: 'lmstudio', name: 'LMStudio', api: 'http://127.0.0.1:1234/v1' },
  { id: 'lucidquery', name: 'LucidQuery AI', api: 'https://lucidquery.com/api/v1' },
  { id: 'meganova', name: 'Meganova', api: 'https://api.meganova.ai/v1' },
  { id: 'merge-gateway', name: 'Merge Gateway', api: '' },
  { id: 'minimax', name: 'MiniMax (minimax.io)', api: 'https://api.minimax.io/anthropic/v1' },
  { id: 'minimax-cn', name: 'MiniMax (minimaxi.com)', api: 'https://api.minimaxi.com/anthropic/v1' },
  { id: 'minimax-coding-plan', name: 'MiniMax Token Plan (minimax.io)', api: 'https://api.minimax.io/anthropic/v1' },
  { id: 'minimax-cn-coding-plan', name: 'MiniMax Token Plan (minimaxi.com)', api: 'https://api.minimaxi.com/anthropic/v1' },
  { id: 'mistral', name: 'Mistral', api: '' },
  { id: 'mixlayer', name: 'Mixlayer', api: 'https://models.mixlayer.ai/v1' },
  { id: 'moark', name: 'Moark', api: 'https://moark.com/v1' },
  { id: 'modelscope', name: 'ModelScope', api: 'https://api-inference.modelscope.cn/v1' },
  { id: 'moonshotai', name: 'Moonshot AI', api: 'https://api.moonshot.ai/v1' },
  { id: 'moonshotai-cn', name: 'Moonshot AI (China)', api: 'https://api.moonshot.cn/v1' },
  { id: 'morph', name: 'Morph', api: 'https://api.morphllm.com/v1' },
  { id: 'nano-gpt', name: 'NanoGPT', api: 'https://nano-gpt.com/api/v1' },
  { id: 'nearai', name: 'NEAR AI Cloud', api: 'https://cloud-api.near.ai/v1' },
  { id: 'nebius', name: 'Nebius Token Factory', api: 'https://api.tokenfactory.nebius.com/v1' },
  { id: 'neuralwatt', name: 'Neuralwatt', api: 'https://api.neuralwatt.com/v1' },
  { id: 'nova', name: 'Nova', api: 'https://api.nova.amazon.com/v1' },
  { id: 'novita-ai', name: 'NovitaAI', api: 'https://api.novita.ai/openai' },
  { id: 'nvidia', name: 'Nvidia', api: 'https://integrate.api.nvidia.com/v1' },
  { id: 'ollama-cloud', name: 'Ollama Cloud', api: 'https://ollama.com/v1' },
  { id: 'openai', name: 'OpenAI', api: '' },
  { id: 'opencode-go', name: 'OpenCode Go', api: 'https://opencode.ai/zen/go/v1' },
  { id: 'opencode', name: 'OpenCode Zen', api: 'https://opencode.ai/zen/v1' },
  { id: 'openrouter', name: 'OpenRouter', api: 'https://openrouter.ai/api/v1' },
  { id: 'orcarouter', name: 'OrcaRouter', api: 'https://api.orcarouter.ai/v1' },
  { id: 'ovhcloud', name: 'OVHcloud AI Endpoints', api: 'https://oai.endpoints.kepler.ai.cloud.ovh.net/v1' },
  { id: 'perplexity', name: 'Perplexity', api: '' },
  { id: 'perplexity-agent', name: 'Perplexity Agent', api: 'https://api.perplexity.ai/v1' },
  { id: 'poe', name: 'Poe', api: 'https://api.poe.com/v1' },
  { id: 'poolside', name: 'Poolside', api: 'https://inference.poolside.ai/v1' },
  { id: 'privatemode-ai', name: 'Privatemode AI', api: 'http://localhost:8080/v1' },
  { id: 'qihang-ai', name: 'QiHang', api: 'https://api.qhaigc.net/v1' },
  { id: 'qiniu-ai', name: 'Qiniu', api: 'https://api.qnaigc.com/v1' },
  { id: 'regolo-ai', name: 'Regolo AI', api: 'https://api.regolo.ai/v1' },
  { id: 'requesty', name: 'Requesty', api: 'https://router.requesty.ai/v1' },
  { id: 'routing-run', name: 'routing.run', api: 'https://ai.routing.sh/v1' },
  { id: 'sap-ai-core', name: 'SAP AI Core', api: '' },
  { id: 'sarvam', name: 'Sarvam AI', api: 'https://api.sarvam.ai/v1' },
  { id: 'scaleway', name: 'Scaleway', api: 'https://api.scaleway.ai/v1' },
  { id: 'siliconflow', name: 'SiliconFlow', api: 'https://api.siliconflow.com/v1' },
  { id: 'siliconflow-cn', name: 'SiliconFlow (China)', api: 'https://api.siliconflow.cn/v1' },
  // eslint-disable-next-line no-template-curly-in-string
  { id: 'snowflake-cortex', name: 'Snowflake Cortex', api: 'https://${SNOWFLAKE_ACCOUNT}.snowflakecomputing.com/api/v2/cortex/v1' },
  { id: 'stackit', name: 'STACKIT', api: 'https://api.openai-compat.model-serving.eu01.onstackit.cloud/v1' },
  { id: 'stepfun-ai', name: 'StepFun', api: 'https://api.stepfun.ai/step_plan/v1' },
  { id: 'stepfun', name: 'StepFun (China)', api: 'https://api.stepfun.com/v1' },
  { id: 'submodel', name: 'submodel', api: 'https://llm.submodel.ai/v1' },
  { id: 'synthetic', name: 'Synthetic', api: 'https://api.synthetic.new/openai/v1' },
  { id: 'tencent-coding-plan', name: 'Tencent Coding Plan (China)', api: 'https://api.lkeap.cloud.tencent.com/coding/v3' },
  { id: 'tencent-tokenhub', name: 'Tencent TokenHub', api: 'https://tokenhub.tencentmaas.com/v1' },
  { id: 'the-grid-ai', name: 'The Grid AI', api: 'https://api.thegrid.ai/v1' },
  { id: 'togetherai', name: 'Together AI', api: '' },
  { id: 'umans-ai-coding-plan', name: 'Umans AI Coding Plan', api: 'https://api.code.umans.ai/v1' },
  { id: 'upstage', name: 'Upstage', api: 'https://api.upstage.ai/v1/solar' },
  { id: 'v0', name: 'v0', api: '' },
  { id: 'venice', name: 'Venice AI', api: '' },
  { id: 'vercel', name: 'Vercel AI Gateway', api: '' },
  { id: 'google-vertex', name: 'Vertex', api: '' },
  { id: 'google-vertex-anthropic', name: 'Vertex (Anthropic)', api: '' },
  { id: 'vivgrid', name: 'Vivgrid', api: 'https://api.vivgrid.com/v1' },
  { id: 'vultr', name: 'Vultr', api: 'https://api.vultrinference.com/v1' },
  { id: 'wafer.ai', name: 'Wafer', api: 'https://pass.wafer.ai/v1' },
  { id: 'wandb', name: 'Weights & Biases', api: 'https://api.inference.wandb.ai/v1' },
  { id: 'xai', name: 'xAI', api: '' },
  { id: 'xiaomi', name: 'Xiaomi', api: 'https://api.xiaomimimo.com/v1' },
  { id: 'xiaomi-token-plan-cn', name: 'Xiaomi Token Plan (China)', api: 'https://token-plan-cn.xiaomimimo.com/v1' },
  { id: 'xiaomi-token-plan-ams', name: 'Xiaomi Token Plan (Europe)', api: 'https://token-plan-ams.xiaomimimo.com/v1' },
  { id: 'xiaomi-token-plan-sgp', name: 'Xiaomi Token Plan (Singapore)', api: 'https://token-plan-sgp.xiaomimimo.com/v1' },
  { id: 'xpersona', name: 'Xpersona', api: 'https://www.xpersona.co/v1' },
  { id: 'zai', name: 'Z.AI', api: 'https://api.z.ai/api/paas/v4' },
  { id: 'zai-coding-plan', name: 'Z.AI Coding Plan', api: 'https://api.z.ai/api/coding/paas/v4' },
  { id: 'zenmux', name: 'ZenMux', api: 'https://zenmux.ai/api/v1' },
  { id: 'zhipuai', name: 'Zhipu AI', api: 'https://open.bigmodel.cn/api/paas/v4' },
  { id: 'zhipuai-coding-plan', name: 'Zhipu AI Coding Plan', api: 'https://open.bigmodel.cn/api/coding/paas/v4' },
]
