import { CONSOLE_BOOTSTRAP } from './console'

export const DESIGN_PICKER_SOURCE = 'emty-design-picker'
export const DESIGN_PICKER_HOST_SOURCE = 'emty-design-picker-host'

export const DESIGN_PICKER_BOOTSTRAP = `<script>(function(){
  var PICKER_ROOT_ID='__emty_design_picker__';
  var PICKER_STYLE_ID='__emty_design_picker_styles__';
  var pickerState={active:false,hovered:null,selected:null,root:null,hoverBox:null,markerLayer:null,composer:null,annotations:[],raf:0,markerListenersActive:false};
  function normalizeText(v){return String(v==null?'':v).replace(/\\s+/g,' ').trim();}
  function truncate(v,max){var t=normalizeText(v);return t.length>max?t.slice(0,max)+'...':t;}
  function truncateRaw(v,max){var t=String(v==null?'':v);return t.length>max?t.slice(0,max)+'...':t;}
  function isVisible(el){if(!(el instanceof HTMLElement))return false;var r=el.getBoundingClientRect();var s=window.getComputedStyle(el);return r.width>0&&r.height>0&&s.visibility!=='hidden'&&s.display!=='none';}
  function elementText(el){return normalizeText(el.getAttribute('aria-label')||el.innerText||el.textContent||'');}
  function elementRole(el){return el.getAttribute('role')||null;}
  function elementIdentifier(el){if(el.id)return '#'+el.id;if(el.getAttribute('name'))return el.tagName.toLowerCase()+'[name="'+el.getAttribute('name')+'"]';if(el.classList.length>0)return el.tagName.toLowerCase()+'.'+Array.prototype.slice.call(el.classList,0,2).join('.');return el.tagName.toLowerCase();}
  function cssEscape(value){if(window.CSS&&typeof window.CSS.escape==='function')return window.CSS.escape(String(value));return String(value).replace(/[^a-zA-Z0-9_-]/g,function(ch){return '\\\\'+ch});}
  function selectorForElement(el){if(!(el instanceof Element))return '';if(el.id)return '#'+cssEscape(el.id);var parts=[];var cur=el;while(cur&&cur instanceof Element&&cur!==document.documentElement){var part=cur.tagName.toLowerCase();var parent=cur.parentElement;if(!parent)break;var same=Array.prototype.slice.call(parent.children).filter(function(c){return c.tagName===cur.tagName});if(same.length>1)part+=':nth-of-type('+(same.indexOf(cur)+1)+')';parts.unshift(part);if(parts.length>=6)break;cur=parent;}return parts.join(' > ')||elementIdentifier(el);}
  function elementAttributes(el){var out={};var attrs=Array.prototype.slice.call(el.attributes||[]);for(var i=0;i<attrs.length;i++){var a=attrs[i];out[a.name]=truncateRaw(a.value,300);}return out;}
  function describeElement(el,opts){opts=opts||{};var r=el.getBoundingClientRect();var needsMax=opts.maxHtmlChars==null?4000:opts.maxHtmlChars;var val='value' in el?String(el.value==null?'':el.value):'';var checked='checked' in el?Boolean(el.checked):undefined;return {tag:el.tagName.toLowerCase(),id:el.id||null,classes:Array.prototype.slice.call(el.classList),name:el.getAttribute('name'),role:elementRole(el),ariaLabel:el.getAttribute('aria-label'),selector:selectorForElement(el),selectorHint:elementIdentifier(el),text:truncate(elementText(el),220),href:el instanceof HTMLAnchorElement?el.href:null,attributes:elementAttributes(el),outerHTML:truncateRaw(el.outerHTML||'',needsMax),placeholder:el.getAttribute('placeholder'),type:'type' in el?String(el.type==null?'':el.type):null,disabled:'disabled' in el?Boolean(el.disabled):false,checked:checked,valuePreview:val?truncate(val,120):null,rect:{x:Math.round(r.x),y:Math.round(r.y),width:Math.round(r.width),height:Math.round(r.height)}};}
  function installPickerStyles(){if(document.getElementById(PICKER_STYLE_ID))return;var s=document.createElement('style');s.id=PICKER_STYLE_ID;s.textContent='#'+PICKER_ROOT_ID+'{position:fixed;inset:0;z-index:2147483647;pointer-events:none;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#f8fbff} #'+PICKER_ROOT_ID+' *{box-sizing:border-box} .emty-picker-hover,.emty-picker-marker-box{position:fixed;border:2px solid #178cff;background:rgba(23,140,255,0.16);box-shadow:0 0 0 1px rgba(255,255,255,0.76),0 10px 32px rgba(0,0,0,0.18);pointer-events:none} .emty-picker-hover{display:none} .emty-picker-pin,.emty-picker-marker-pin{position:fixed;display:grid;place-items:center;width:22px;height:22px;border:2px solid #ffffff;border-radius:999px;background:#178cff;box-shadow:0 6px 18px rgba(0,0,0,0.25);pointer-events:none} .emty-picker-pin::before,.emty-picker-marker-pin::before{content:"";width:8px;height:8px;border-radius:999px;background:#ffffff} .emty-picker-composer{position:fixed;width:min(300px,calc(100vw - 24px));border:1px solid #262626;border-radius:12px;background:#0a0a0a;box-shadow:0 12px 32px rgba(0,0,0,0.45),0 2px 8px rgba(0,0,0,0.3);padding:6px;pointer-events:auto} .emty-picker-composer-row{display:flex;align-items:center;gap:8px} .emty-picker-comment{flex:1;min-width:0;height:28px;box-sizing:border-box;border:1px solid #333333;border-radius:8px;outline:0;resize:none;background:#141414;color:#f2f2f2;font:inherit;font-size:12px;line-height:20px;padding:4px 8px;transition:border-color 150ms ease} .emty-picker-comment:focus{border-color:#00e5ff} .emty-picker-comment::placeholder{color:#595959} .emty-picker-action,.emty-picker-cancel{display:grid;place-items:center;width:28px;height:28px;flex-shrink:0;border:1px solid #333333;border-radius:8px;background:#141414;color:#8a8a8a;cursor:pointer;font:inherit;transition:background 100ms cubic-bezier(0.4,0,0.2,1),border-color 100ms cubic-bezier(0.4,0,0.2,1),color 100ms cubic-bezier(0.4,0,0.2,1)} .emty-picker-cancel:hover{background:#1c1c1c;color:#f2f2f2} .emty-picker-cancel:active{transform:scale(0.97)} .emty-picker-action:disabled{cursor:default;opacity:0.45} .emty-picker-action:not(:disabled){border-color:rgba(0,229,255,0.4);background:rgba(0,229,255,0.18);color:#00e5ff} .emty-picker-action:not(:disabled):hover{background:rgba(0,229,255,0.28)} .emty-picker-action:not(:disabled):active{transform:scale(0.97)} .emty-picker-marker-note{position:fixed;max-width:260px;padding:7px 10px;border-radius:12px;background:#178cff;color:#ffffff;font-size:12px;font-weight:600;line-height:1.35;box-shadow:0 8px 22px rgba(0,0,0,0.25);pointer-events:none}';(document.head||document.documentElement).appendChild(s);}
  function ensurePickerRoot(){installPickerStyles();if(pickerState.root&&document.documentElement.contains(pickerState.root))return pickerState.root;var root=document.createElement('div');root.id=PICKER_ROOT_ID;var hoverBox=document.createElement('div');hoverBox.className='emty-picker-hover';var pin=document.createElement('div');pin.className='emty-picker-pin';hoverBox.appendChild(pin);var markerLayer=document.createElement('div');markerLayer.className='emty-picker-marker-layer';root.appendChild(markerLayer);root.appendChild(hoverBox);document.documentElement.appendChild(root);pickerState.root=root;pickerState.hoverBox=hoverBox;pickerState.markerLayer=markerLayer;return root;}
  function isPickerElement(n){return n instanceof Element&&!!n.closest('#'+PICKER_ROOT_ID);}
  function elementFromPointer(e){var el=document.elementFromPoint(e.clientX,e.clientY);if(!el||isPickerElement(el)||el===document.documentElement||el===document.body)return null;return el;}
  function positionBox(box,rect){var left=rect.left;var top=rect.top;var width=rect.width;var height=rect.height;var right=rect.right;box.style.display='block';box.style.left=Math.max(0,Math.round(left))+'px';box.style.top=Math.max(0,Math.round(top))+'px';box.style.width=Math.max(1,Math.round(width))+'px';box.style.height=Math.max(1,Math.round(height))+'px';var pin=box.querySelector('.emty-picker-pin, .emty-picker-marker-pin');if(pin){pin.style.left=Math.min(window.innerWidth-26,Math.max(4,Math.round(right-12)))+'px';pin.style.top=Math.min(window.innerHeight-26,Math.max(4,Math.round(top+height/2-11)))+'px';}}
  function updateHoverBox(){if(!pickerState.hoverBox||!pickerState.hovered)return;positionBox(pickerState.hoverBox,pickerState.hovered.getBoundingClientRect());}
  function hideHoverBox(){if(pickerState.hoverBox)pickerState.hoverBox.style.display='none';}
  function scheduleMarkerRender(){if(pickerState.raf)return;pickerState.raf=window.requestAnimationFrame(function(){pickerState.raf=0;renderPickerMarkers();updateHoverBox();});}
  function syncMarkerListeners(){var should=pickerState.active||pickerState.annotations.length>0;if(should===pickerState.markerListenersActive)return;pickerState.markerListenersActive=should;var m=should?'addEventListener':'removeEventListener';window[m]('scroll',scheduleMarkerRender,true);window[m]('resize',scheduleMarkerRender,true);}
  function renderPickerMarkers(){ensurePickerRoot();var layer=pickerState.markerLayer;if(!layer)return;layer.textContent='';for(var i=0;i<pickerState.annotations.length;i++){var ann=pickerState.annotations[i];if(!ann||!ann.element||!ann.element.selector)continue;var el=null;try{el=document.querySelector(ann.element.selector);}catch(e){el=null;}if(!el||!isVisible(el))continue;var rect=el.getBoundingClientRect();var box=document.createElement('div');box.className='emty-picker-marker-box';var p=document.createElement('div');p.className='emty-picker-marker-pin';box.appendChild(p);positionBox(box,rect);var note=document.createElement('div');note.className='emty-picker-marker-note';note.textContent=truncate(ann.comment,90);note.style.left=Math.min(window.innerWidth-272,Math.max(8,Math.round(rect.left)))+'px';note.style.top=Math.min(window.innerHeight-48,Math.max(8,Math.round(rect.bottom+8)))+'px';layer.appendChild(box);layer.appendChild(note);}}
  function removeComposer(){if(pickerState.composer){pickerState.composer.remove();pickerState.composer=null;}pickerState.selected=null;}
  function showComposerFor(el){ensurePickerRoot();removeComposer();pickerState.selected=el;var rect=el.getBoundingClientRect();var c=document.createElement('div');c.className='emty-picker-composer';c.innerHTML='<div class="emty-picker-composer-row"><button class="emty-picker-cancel" type="button" aria-label="Cancel annotation"><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M18 6 6 18"/><path d="m6 6 12 12"/></svg></button><textarea class="emty-picker-comment" rows="1" placeholder="Add a comment..."></textarea><button class="emty-picker-action" type="button" aria-label="Attach comment" disabled><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14"/><path d="M12 5v14"/></svg></button></div>';var left=Math.min(window.innerWidth-332,Math.max(12,rect.left+rect.width/2-160));var below=rect.bottom+10;var top=below+58<window.innerHeight?below:Math.max(12,rect.top-58);c.style.left=left+'px';c.style.top=top+'px';var ta=c.querySelector('.emty-picker-comment');var act=c.querySelector('.emty-picker-action');var canc=c.querySelector('.emty-picker-cancel');ta.addEventListener('input',function(){act.disabled=ta.value.trim().length===0;});ta.addEventListener('keydown',function(e){if(e.key==='Escape'){e.preventDefault();removeComposer();}if((e.key==='Enter'&&(e.metaKey||e.ctrlKey))||(e.key==='Enter'&&!e.shiftKey)){e.preventDefault();submitPickerComment(ta.value);}});act.addEventListener('click',function(){submitPickerComment(ta.value);});canc.addEventListener('click',removeComposer);pickerState.root.appendChild(c);pickerState.composer=c;setTimeout(function(){ta.focus();},0);}
  function makePickerId(){if(window.crypto&&typeof window.crypto.randomUUID==='function')return window.crypto.randomUUID();return 'design-element-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8);}
  function submitPickerComment(raw){var comment=normalizeText(raw);var el=pickerState.selected;if(!comment||!el)return;var ann={id:makePickerId(),comment:comment,url:window.location.href,title:document.title,createdAt:Date.now(),element:describeElement(el,{maxHtmlChars:6000})};pickerState.annotations.push(ann);removeComposer();renderPickerMarkers();try{parent.postMessage({source:'emty-design-picker',kind:'annotation',annotation:ann},'*');}catch(e){}}
  function onPickerPointerMove(e){if(!pickerState.active||pickerState.composer)return;var el=elementFromPointer(e);if(el===pickerState.hovered)return;pickerState.hovered=el;if(!el){hideHoverBox();return;}updateHoverBox();}
  function onPickerPointerDown(e){if(!pickerState.active)return;if(isPickerElement(e.target))return;var el=elementFromPointer(e);if(!el)return;e.preventDefault();e.stopPropagation();showComposerFor(el);}
  function onPickerClick(e){if(!pickerState.active||isPickerElement(e.target))return;e.preventDefault();e.stopPropagation();}
  function onPickerKeydown(e){if(!pickerState.active)return;if(e.key==='Escape'){e.preventDefault();stopPicker();}}
  function startPicker(){ensurePickerRoot();if(pickerState.active)return;pickerState.active=true;document.addEventListener('pointermove',onPickerPointerMove,true);document.addEventListener('pointerdown',onPickerPointerDown,true);document.addEventListener('click',onPickerClick,true);document.addEventListener('keydown',onPickerKeydown,true);syncMarkerListeners();renderPickerMarkers();}
  function stopPicker(){if(!pickerState.active)return;pickerState.active=false;pickerState.hovered=null;document.removeEventListener('pointermove',onPickerPointerMove,true);document.removeEventListener('pointerdown',onPickerPointerDown,true);document.removeEventListener('click',onPickerClick,true);document.removeEventListener('keydown',onPickerKeydown,true);removeComposer();hideHoverBox();syncMarkerListeners();}
  function setAnnotations(list){pickerState.annotations=Array.isArray(list)?list:[];renderPickerMarkers();syncMarkerListeners();}
  window.__EMTY_DESIGN_PICKER__={start:startPicker,stop:stopPicker,setAnnotations:setAnnotations};
  window.addEventListener('message',function(e){try{var d=e.data;if(!d||d.source!=='emty-design-picker-host')return;if(d.action==='startPicker')startPicker();else if(d.action==='stopPicker')stopPicker();else if(d.action==='setAnnotations')setAnnotations(d.annotations||[]);}catch(err){}});
})();<\/script>`

export function injectPickerBootstrap(html: string): string {
  // Insert picker bootstrap right after console bootstrap if present, else after <head>.
  const consoleIdx = html.indexOf(CONSOLE_BOOTSTRAP)
  if (consoleIdx !== -1) {
    const insertAt = consoleIdx + CONSOLE_BOOTSTRAP.length
    return html.slice(0, insertAt) + DESIGN_PICKER_BOOTSTRAP + html.slice(insertAt)
  }
  // Fallback: console marker exists but CONSOLE_BOOTSTRAP not matched verbatim (e.g. minified) — find the first </script> after the marker
  if (html.includes('emty-design-console')) {
    const markerIdx = html.indexOf('emty-design-console')
    const closeIdx = html.indexOf('</script>', markerIdx)
    if (closeIdx !== -1) {
      const insertAt = closeIdx + '</script>'.length
      return html.slice(0, insertAt) + DESIGN_PICKER_BOOTSTRAP + html.slice(insertAt)
    }
  }
  const headMatch = /<head[^>]*>/i.exec(html)
  if (headMatch && headMatch.index !== undefined) {
    const idx = headMatch.index + headMatch[0].length
    return html.slice(0, idx) + DESIGN_PICKER_BOOTSTRAP + html.slice(idx)
  }
  return DESIGN_PICKER_BOOTSTRAP + html
}
