export function buildCommitPrompt(diff: string, stat = ''): string {
  const MAX_DIFF_CHARS = 14_000
  let trimmed = diff ?? ''
  let truncatedNote = ''
  if (trimmed.length > MAX_DIFF_CHARS) {
    trimmed = trimmed.slice(0, MAX_DIFF_CHARS)
    truncatedNote = `\n\n[NOTE: diff truncated to ${MAX_DIFF_CHARS} characters]`
  }

  const statBlock = stat.trim()
    ? `\n# Staged Diff Stat\n\n<stat>\n${stat.trim()}\n</stat>\n`
    : ''

  return `You are an expert software engineer generating a production-quality Git commit message.

# Required Format

Use Conventional Commits:

<type>(<scope>): <specific summary>

- <specific change and why it matters>
- <specific behavior, safety detail, or module-level impact>
- <specific follow-on detail, if present>

# Type Prefixes

- \`feat\` - a new feature
- \`fix\` - a bug fix
- \`docs\` - documentation only
- \`style\` - formatting only, no logic change
- \`refactor\` - restructuring code without changing behavior
- \`perf\` - performance improvement
- \`test\` - adding or updating tests
- \`build\` - build system or dependencies
- \`ci\` - CI/CD configuration
- \`chore\` - other maintenance
- \`revert\` - reverting a previous commit

# Accuracy Rules

1. Use imperative mood: "Add", "Fix", "Remove", "Guard".
2. Keep the subject under 72 characters.
3. Include a detailed body unless the diff is truly trivial.
4. Use 2-5 body bullets for multi-file or behavioral changes.
5. Explain what changed and why it matters.
6. Mention safeguards, migrations, user-facing behavior, and tests only if
   they are visible in the diff.
7. Do not invent files, tests, risks, or behavior.
8. Prefer concrete component/module names over vague wording.
9. Do not include markdown code fences.
10. Do not include "Generated by", "AI", or co-author trailers.

Base the message only on the staged diff and stat below.${statBlock}

# Staged Diff

<diff>
${trimmed}
</diff>
${truncatedNote}

Generate the commit message now.`
}
