export function buildCommitPrompt(diff: string, stat = ''): string {
  const MAX_DIFF_CHARS = 14_000
  let trimmed = diff ?? ''
  let truncatedNote = ''
  if (trimmed.length > MAX_DIFF_CHARS) {
    trimmed = trimmed.slice(0, MAX_DIFF_CHARS)
    truncatedNote = `\n\n[NOTE: diff truncated to ${MAX_DIFF_CHARS} characters]`
  }

  const statBlock = stat.trim()
    ? `\n# Staged Diff Stat\n\n<stat>\n${stat.trim()}\n</stat>\n`
    : ''

  return `You are an expert software engineer generating a production-quality Git commit message.

# Required Format

Use Conventional Commits with a detailed categorized body:

<type>(<scope>): <imperative summary under 72 chars>

<one-line summary of the overall change>

<Category>:
- <specific change>
- <specific change>

<Another Category>:
- <specific change>
- <specific change>

# Structure Rules

1. The subject line uses Conventional Commits format and stays under 72 chars.
2. After the subject, write a single blank line, then a one-line summary of the
   entire changeset (what it accomplishes at a high level).
3. Group changes into named categories based on the area of the codebase they
   affect (e.g. "Sidepane architecture:", "Chat input overlay refactor:",
   "Store restructure:", "Utilities:", "Other:"). Use descriptive category names
   that match the nature of the grouping, not generic labels.
4. Under each category, list every meaningful change as an indented dash-prefixed
   bullet. Each bullet should describe one concrete action or change using
   imperative mood ("Add", "Extract", "Move", "Simplify", "Update", "Remove").
5. Reference specific file names, component names, store names, and module paths
   in bullets so the reader can trace changes.
6. For moved/renamed files, note the old and new paths.
7. For new files, start bullets with "Add". For deleted files, start with "Remove"
   or "Delete".
8. Include a line count summary at the top of the body (e.g. "N files changed
   (+X / -Y lines)") if available from the diff stat.

# Type Prefixes

- \`feat\` - a new feature
- \`fix\` - a bug fix
- \`docs\` - documentation only
- \`style\` - formatting only, no logic change
- \`refactor\` - restructuring code without changing behavior
- \`perf\` - performance improvement
- \`test\` - adding or updating tests
- \`build\` - build system or dependencies
- \`ci\` - CI/CD configuration
- \`chore\` - other maintenance
- \`revert\` - reverting a previous commit

# Accuracy Rules

1. Use imperative mood throughout: "Add", "Fix", "Remove", "Guard".
2. Explain what changed and why it matters at the module level.
3. Mention migrations, user-facing behavior, and tests only if visible in the diff.
4. Do not invent files, tests, risks, or behavior not present in the diff.
5. Prefer concrete component/module names over vague wording.
6. Do not include markdown code fences.
7. Do not include "Generated by", "AI", or co-author trailers.
8. For small trivial diffs (single file, under 20 lines), a short subject +
   1-2 sentence body is fine. Skip categories.

Base the message only on the staged diff and stat below.${statBlock}

# Staged Diff

<diff>
${trimmed}
</diff>
${truncatedNote}

Generate the commit message now.`
}
