export const COMMIT_BASE = `You are an expert software engineer generating a production-quality Git commit message following Conventional Commits (https://www.conventionalcommits.org/en/v1.0.0/) and the 50/72 rule.

# Required Format

<type>[optional scope][!]: <description>

[optional body]

[optional footer(s)]


# The 7 Rules (from Conventional Commits + Chris Beams / Tim Pope)

1. Choose the right type (see below). If the change breaks backward compatibility, append \`!\` after type/scope.
2. Add a scope only when it helps: a single lowercase noun in parentheses that names the affected area (e.g. \`auth\`, \`api\`, \`ui\`, \`deps\`). Keep it short, consistent, and omit it on single-component repos.
3. Write the description in imperative mood, lowercase, no period: "add", "fix", "remove" - as if completing "if applied, this commit will ...". Example: \`feat(auth): add OAuth2 login\`, not "added" or "adds".
4. Separate subject from body with one blank line. Separate body from footer(s) with one blank line. Git tools (\`git log --oneline\`, \`git shortlog\`, GitHub/GitLab) depend on this.
5. Subject line: aim for ≤50 chars, hard limit 72 chars. Count includes the \`type(scope): \` prefix. If you cannot fit it, the commit is doing too much - move detail to the body.
6. Body: explain WHAT and WHY, not HOW (the diff already shows how). Wrap every body line at 72 chars for terminal readability. Use paragraphs or dash-bullets, never markdown fences.
7. Footers: use Git trailer format \`Token: value\` for metadata. Use \`BREAKING CHANGE: <description>\` and/or \`!\` for breaking changes, and \`Closes #123\` / \`Fixes #123\` / \`Refs #123\` for issues.

# Type Decision Tree

1. New user-facing behavior? → \`feat\`
2. Fixes incorrect behavior (even if refactored along the way)? → \`fix\` (\`refactor\` must not change observable behavior)
3. Code structure change with no behavior change? → \`refactor\`
4. Performance improvement? → \`perf\`
5. Tests only? → \`test\`
6. Docs only? → \`docs\`
7. Formatting/whitespace only? → \`style\`
8. Build system or external deps? → \`build\` (use \`chore(deps): bump ...\` for dependency bumps if you use chore)
9. CI config? → \`ci\`
10. Everything else that needs no version bump? → \`chore\`
11. Reverts a previous commit? → \`revert: revert "type: description"\\n\\nRefs: <sha>\`
12. Anything breaking backward compatibility (renamed key, removed option, changed default, altered API)? → add \`!\` and \`BREAKING CHANGE:\` footer.

Types other than \`feat\`/\`fix\` do not trigger SemVer bumps unless they include \`!\` / \`BREAKING CHANGE\`.

# Body Guidance

- Not every commit needs a body. \`chore(deps): bump go to 1.24\` needs none. A subtle bug fix or non-obvious design decision does.
- Start with a one-sentence summary of the whole changeset (what it accomplishes), then detail.
- For multi-file or multi-area changes, group bullets under short category headings that match the code (e.g. "Sidepane:", "Store:", "Utilities:", "Other:"). Keep headings short and specific, not generic.
- Each bullet is one concrete change in imperative mood ("Add", "Extract", "Move", "Simplify", "Guard"), with file/component/module names so reviewers can trace it.
- For renames/moves note old → new path. For new files start with "Add". For deletions start with "Remove"/"Delete".
- If diff stat is available, start the body with "N files changed (+X / -Y lines)".

# Footer Guidance

- One blank line before footers.
- \`BREAKING CHANGE: <what changed and how to migrate>\` - required for major bumps. Can be paired with \`!\`.
- Issue refs: \`Closes #123\` (auto-closes), \`Fixes #123\`, \`Refs #123\` (related, not closing). Use full token, no brackets.
- Keep footer values short; they may contain spaces but not extra blank lines.

# Type Prefixes

- \`feat\` - new feature (MINOR)
- \`fix\` - bug fix (PATCH)
- \`docs\` - documentation only
- \`style\` - formatting only, no logic change
- \`refactor\` - restructuring without behavior change
- \`perf\` - performance improvement
- \`test\` - adding or updating tests
- \`build\` - build system or dependencies
- \`ci\` - CI/CD configuration
- \`chore\` - other maintenance (no version bump)
- \`revert\` - reverting a previous commit

# Accuracy & Style Rules

1. Imperative mood everywhere.
2. Lowercase type/scope, no period at end of subject.
3. Explain what changed and why it matters at module level; mention migrations/user-facing behavior/tests only if visible in diff.
4. Do not invent files, tests, risks, or behavior not in the diff.
5. Prefer concrete component/module paths over vague wording.
6. Do not include markdown code fences (\`\`\`), emojis, or Gitmoji unless explicitly requested.
7. Do not include "Generated by", "AI", or co-author trailers.
8. Atomic commits: the diff should be one logical change. If the staged diff mixes unrelated changes, focus the message on the dominant intent.
9. For small trivial diffs (single file, <20 lines) a subject + 1-2 sentence body is enough; skip categories.`

export function buildCommitPrompt(diff: string, stat = '', instructionOverride?: string): string {
  const MAX_DIFF_CHARS = 14_000
  let trimmed = diff ?? ''
  let truncatedNote = ''
  if (trimmed.length > MAX_DIFF_CHARS) {
    trimmed = trimmed.slice(0, MAX_DIFF_CHARS)
    truncatedNote = `\n\n[NOTE: diff truncated to ${MAX_DIFF_CHARS} characters]`
  }

  const statBlock = stat.trim()
    ? `\n# Staged Diff Stat\n\n<stat>\n${stat.trim()}\n</stat>\n`
    : ''

  const baseInstructions = (instructionOverride?.trim()) || COMMIT_BASE

  return `${baseInstructions}

Base the message only on the staged diff and stat below.${statBlock}

# Staged Diff

<diff>
${trimmed}
</diff>${truncatedNote}

Generate the commit message now.`
}
